const STATUS_CODES = {
    OK: 200,
    BAD_REQUEST: 400,
    UNAUTHORIZED: 401,
    FORBIDDEN: 403,
    NOT_FOUND: 404,
    INTERNAL_SERVER_ERROR: 500,
    OK_CREATED: 201,
    UNPROCESSABLE_ENTITY: 422
  };
  
  module.exports = STATUS_CODES;
  
